//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSitesi.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class French {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal French() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaberSitesi.Lang.French", typeof(French).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de WorldsNewsPoint.com.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue au point de nouvelles du monde! &lt;br /&gt;
        ///Voici le site nouvelles que tout le monde peut facilement utiliser, partout dans le monde,&lt;br /&gt;
        ///les gens peuvent personnaliser leur propre flux de nouvelles ici,&lt;br /&gt;
        ///il y a plus de nouvelles fonctionnalités à découvrir sur ce site.&lt;br /&gt;.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter Des Nouvelles.
        /// </summary>
        internal static string BtnAddNews {
            get {
                return ResourceManager.GetString("BtnAddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affaires.
        /// </summary>
        internal static string BtnBusiness {
            get {
                return ResourceManager.GetString("BtnBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Santé.
        /// </summary>
        internal static string BtnHealth {
            get {
                return ResourceManager.GetString("BtnHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;identifier.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-Out.
        /// </summary>
        internal static string BtnLogout {
            get {
                return ResourceManager.GetString("BtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Science.
        /// </summary>
        internal static string BtnScience {
            get {
                return ResourceManager.GetString("BtnScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réglages.
        /// </summary>
        internal static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        internal static string BtnSignUp {
            get {
                return ResourceManager.GetString("BtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Sport.
        /// </summary>
        internal static string BtnSport {
            get {
                return ResourceManager.GetString("BtnSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Technologie.
        /// </summary>
        internal static string BtnTech {
            get {
                return ResourceManager.GetString("BtnTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidéo.
        /// </summary>
        internal static string BtnVideo {
            get {
                return ResourceManager.GetString("BtnVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monde.
        /// </summary>
        internal static string BtnWorld {
            get {
                return ResourceManager.GetString("BtnWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commenter.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez écrire quelque chose à commenter!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos de nous.
        /// </summary>
        internal static string LblAbout {
            get {
                return ResourceManager.GetString("LblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter Des Nouvelles.
        /// </summary>
        internal static string LblAddNews {
            get {
                return ResourceManager.GetString("LblAddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie:.
        /// </summary>
        internal static string LblCat {
            get {
                return ResourceManager.GetString("LblCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les nouvelles dans ces catégories:.
        /// </summary>
        internal static string LblCats {
            get {
                return ResourceManager.GetString("LblCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer le mot de passe: &lt;br /&gt; (laissez le champ vide si vous ne voulez pas changer):.
        /// </summary>
        internal static string LblCngPass {
            get {
                return ResourceManager.GetString("LblCngPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le contact.
        /// </summary>
        internal static string LblContact {
            get {
                return ResourceManager.GetString("LblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu: (8000 caractères).
        /// </summary>
        internal static string LblContent {
            get {
                return ResourceManager.GetString("LblContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Description: (500 caractères).
        /// </summary>
        internal static string LblDesc {
            get {
                return ResourceManager.GetString("LblDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Lblemail {
            get {
                return ResourceManager.GetString("Lblemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre: (70 caractères).
        /// </summary>
        internal static string LblHeading {
            get {
                return ResourceManager.GetString("LblHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        internal static string LblHelloEdt {
            get {
                return ResourceManager.GetString("LblHelloEdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour.
        /// </summary>
        internal static string LblHelloUsr {
            get {
                return ResourceManager.GetString("LblHelloUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page d&apos;accueil.
        /// </summary>
        internal static string LblHome {
            get {
                return ResourceManager.GetString("LblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Langue:.
        /// </summary>
        internal static string LblLang {
            get {
                return ResourceManager.GetString("LblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les nouvelles dans ces langues:.
        /// </summary>
        internal static string LblLangs {
            get {
                return ResourceManager.GetString("LblLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe:.
        /// </summary>
        internal static string LblNpass {
            get {
                return ResourceManager.GetString("LblNpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répétez le nouveau mot de passe:.
        /// </summary>
        internal static string LblNPass2 {
            get {
                return ResourceManager.GetString("LblNPass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mot de passe:.
        /// </summary>
        internal static string LblPass {
            get {
                return ResourceManager.GetString("LblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe:.
        /// </summary>
        internal static string LblpassS {
            get {
                return ResourceManager.GetString("LblpassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe actuel:.
        /// </summary>
        internal static string LblPassSettings {
            get {
                return ResourceManager.GetString("LblPassSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réglages.
        /// </summary>
        internal static string LblSettings {
            get {
                return ResourceManager.GetString("LblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        internal static string LblSignUp {
            get {
                return ResourceManager.GetString("LblSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Source:.
        /// </summary>
        internal static string LblSource {
            get {
                return ResourceManager.GetString("LblSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de l&apos;image: (250 caractères).
        /// </summary>
        internal static string LblUrl {
            get {
                return ResourceManager.GetString("LblUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nom d&apos;utilisateur:.
        /// </summary>
        internal static string LblUsr {
            get {
                return ResourceManager.GetString("LblUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur:.
        /// </summary>
        internal static string LblusrS {
            get {
                return ResourceManager.GetString("LblusrS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez vous connecter pour écrire des commentaires.
        /// </summary>
        internal static string LoginToComment {
            get {
                return ResourceManager.GetString("LoginToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Message:.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Prénom:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Source: .
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de Famille:.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écrivez-Nous un Message.
        /// </summary>
        internal static string WriteMessage {
            get {
                return ResourceManager.GetString("WriteMessage", resourceCulture);
            }
        }
    }
}
