//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSitesi.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Turkish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Turkish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaberSitesi.Lang.Turkish", typeof(Turkish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorldsNewsPoint.com Hakkında.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dünyanın haber merkezine hoş geldin!&lt;br /&gt;
        ///				Burası dünyanın her tarafından rahatça kullanılabilecek bir haber sitesi,&lt;br /&gt;
        ///				burada insanlar kendi haber akışlarını özelleştirebilirler,&lt;br /&gt;
        ///				bu özelliklerden faydalanmak için üye olabilirsiniz.&lt;br /&gt;.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Ekle.
        /// </summary>
        internal static string BtnAddNews {
            get {
                return ResourceManager.GetString("BtnAddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticaret.
        /// </summary>
        internal static string BtnBusiness {
            get {
                return ResourceManager.GetString("BtnBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağlık.
        /// </summary>
        internal static string BtnHealth {
            get {
                return ResourceManager.GetString("BtnHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string BtnLogout {
            get {
                return ResourceManager.GetString("BtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilim.
        /// </summary>
        internal static string BtnScience {
            get {
                return ResourceManager.GetString("BtnScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        internal static string BtnSignUp {
            get {
                return ResourceManager.GetString("BtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spor.
        /// </summary>
        internal static string BtnSport {
            get {
                return ResourceManager.GetString("BtnSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknoloji.
        /// </summary>
        internal static string BtnTech {
            get {
                return ResourceManager.GetString("BtnTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string BtnVideo {
            get {
                return ResourceManager.GetString("BtnVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dünya.
        /// </summary>
        internal static string BtnWorld {
            get {
                return ResourceManager.GetString("BtnWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Yap.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alanı boş bırakamazsınız!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string LblAbout {
            get {
                return ResourceManager.GetString("LblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Ekle.
        /// </summary>
        internal static string LblAddNews {
            get {
                return ResourceManager.GetString("LblAddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori:.
        /// </summary>
        internal static string LblCat {
            get {
                return ResourceManager.GetString("LblCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece şu kategorilerden haberleri göster:.
        /// </summary>
        internal static string LblCats {
            get {
                return ResourceManager.GetString("LblCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Değiştirme:&lt;br /&gt;(değiştirmek istemiyorsanız kutuları boş bırakın):.
        /// </summary>
        internal static string LblCngPass {
            get {
                return ResourceManager.GetString("LblCngPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string LblContact {
            get {
                return ResourceManager.GetString("LblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Metni: (8000 karakter).
        /// </summary>
        internal static string LblContent {
            get {
                return ResourceManager.GetString("LblContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısa Açıklama: (500 karakter).
        /// </summary>
        internal static string LblDesc {
            get {
                return ResourceManager.GetString("LblDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Lblemail {
            get {
                return ResourceManager.GetString("Lblemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Başlığı: (70 karakter).
        /// </summary>
        internal static string LblHeading {
            get {
                return ResourceManager.GetString("LblHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldin.
        /// </summary>
        internal static string LblHelloEdt {
            get {
                return ResourceManager.GetString("LblHelloEdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        internal static string LblHelloUsr {
            get {
                return ResourceManager.GetString("LblHelloUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        internal static string LblHome {
            get {
                return ResourceManager.GetString("LblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil:.
        /// </summary>
        internal static string LblLang {
            get {
                return ResourceManager.GetString("LblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece şu dillerdeki haberleri göster:.
        /// </summary>
        internal static string LblLangs {
            get {
                return ResourceManager.GetString("LblLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre:.
        /// </summary>
        internal static string LblNpass {
            get {
                return ResourceManager.GetString("LblNpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre:.
        /// </summary>
        internal static string LblNPass2 {
            get {
                return ResourceManager.GetString("LblNPass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to şifre:.
        /// </summary>
        internal static string LblPass {
            get {
                return ResourceManager.GetString("LblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string LblpassS {
            get {
                return ResourceManager.GetString("LblpassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli Şifre:.
        /// </summary>
        internal static string LblPassSettings {
            get {
                return ResourceManager.GetString("LblPassSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string LblSettings {
            get {
                return ResourceManager.GetString("LblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        internal static string LblSignUp {
            get {
                return ResourceManager.GetString("LblSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Kaynağı:.
        /// </summary>
        internal static string LblSource {
            get {
                return ResourceManager.GetString("LblSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Url&apos;si: (250 karakter).
        /// </summary>
        internal static string LblUrl {
            get {
                return ResourceManager.GetString("LblUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanıcı adı:.
        /// </summary>
        internal static string LblUsr {
            get {
                return ResourceManager.GetString("LblUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string LblusrS {
            get {
                return ResourceManager.GetString("LblusrS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen yorum yapabilmek için giriş yapınız.
        /// </summary>
        internal static string LoginToComment {
            get {
                return ResourceManager.GetString("LoginToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız:.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Kaynağı: .
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim:.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Mesaj Yaz.
        /// </summary>
        internal static string WriteMessage {
            get {
                return ResourceManager.GetString("WriteMessage", resourceCulture);
            }
        }
    }
}
